[platformio]
src_dir = SmartPuckFirmware

[env:lolin_s3_pro]
platform = espressif32
board = lolin_s3_pro
framework = arduino
monitor_speed = 921600

# Let PlatformIO auto-detect the correct port
;upload_port = COM8
;monitor_port = COM8
upload_speed = 115200

build_flags = 
    -DBOARD_LOLIN_S3_PRO
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM

lib_deps =
    greiman/SdFat @ ^2.2.3
